### PR TITLE
update dependencies

### LINKED ISSUE #11: Run dependency updates.
**Describe the bug**
We need to update npm packages.

### PR DESCRIPTION
**Pull request by devPalacio**
Closes #11. Used `npx npm-check-updates -u` and verified tests passed.

### CODE REVIEW

**Review by ambergkim — APPROVED** [review]
Thank you 😇

**Comment by devPalacio** [comment]
```
This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.
```

I know how much you love dealing with GH permissions @ambergkim

**Comment by devPalacio** [comment]
....I tried to rename the branch using our naming conventions, and it closed the issue :(

**Review by ambergkim — APPROVED** [review]
👏

**Pull request merged**
